FROM apache/airflow:2.0.2
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir python-dotenv==0.17.1 requests
RUN chmod 777 /home/airflow/.local/
